import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Holiday Calendar',
  description: 'Generated by Percon',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Holiday Calendar - Generated by Percon</title>
        <meta name="description" content="A comprehensive holiday calendar to keep track of official and religious holidays." />
        <meta name="keywords" content="holiday calendar, official holidays, religious holidays, holiday tracker" />
        <meta name="author" content="Percon" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://holidaylist.vercel.app" />
        <meta property="og:title" content="Holiday Calendar - Track All Holidays" />
        <meta property="og:description" content="Explore the official and religious holidays across various regions with the Holiday Calendar." />
        <meta property="og:image" content="/social-preview.png" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:url" content="https://holidaylist.vercel.app" />
        <meta name="twitter:title" content="Holiday Calendar - Track All Holidays" />
        <meta name="twitter:description" content="Explore the official and religious holidays across various regions with the Holiday Calendar." />
        <meta name="twitter:image" content="/social-preview.png" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body>{children}</body>
    </html>
  );
}
